-- Consolidat SQL Migration for TBP Pulse
-- Acest script creează toate tabelele necesare și configurează securitatea (RLS).
-- Rulează acest script în "SQL Editor" din Supabase.

-- 1. Tabel: Proiecte (Clienți)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    status TEXT DEFAULT 'green',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT,
    progress NUMERIC DEFAULT 0,
    assignees TEXT[] DEFAULT '{}',
    color TEXT,
    icon_name TEXT
);

-- Adaugăm coloanele dacă nu există deja pentru projetele existente
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS progress NUMERIC DEFAULT 0;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS assignees TEXT[] DEFAULT '{}';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS icon_name TEXT;


-- 2. Tabel: Sarcini (Tasks)
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    instructions TEXT,
    deadline TIMESTAMPTZ,
    status TEXT DEFAULT 'todo',
    assignee TEXT,
    project_id BIGINT REFERENCES public.projects(id),
    priority TEXT,
    task_type TEXT,
    block_reason TEXT,
    moved_to_review_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    reviewer TEXT,
    attachments TEXT[] DEFAULT '{}',
    created_by TEXT,
    client TEXT,
    drive_link TEXT,
    extra_link TEXT,
    finished_link TEXT
);

-- Adaugăm coloanele dacă nu există
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS attachments TEXT[] DEFAULT '{}';
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS reviewer TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS client TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS drive_link TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS extra_link TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS finished_link TEXT;


-- 3. Tabel: Alerte (TBP Alerts)
CREATE TABLE IF NOT EXISTS public.tbp_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    client TEXT,
    assignee TEXT,
    assignee_initials TEXT,
    assignee_color TEXT,
    error_code TEXT,
    severity TEXT CHECK (severity IN ('critical', 'warning', 'info')),
    is_resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    resolution_note TEXT,
    read_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel: Tranzacții Financiare (Finance Pulse)
CREATE TABLE IF NOT EXISTS public.tbp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    vendor TEXT,
    category TEXT,
    is_recurring BOOLEAN DEFAULT FALSE,
    type TEXT CHECK (type IN ('income', 'expense')),
    owner_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel: Documents
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    name TEXT NOT NULL,
    size TEXT,
    url TEXT NOT NULL,
    uploader TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabel: Messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    content TEXT NOT NULL,
    sender TEXT,
    sender_full TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabel: Activities
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    user_initials TEXT,
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Creare Storage pentru attachments
INSERT INTO storage.buckets (id, name, public) VALUES ('attachments', 'attachments', true) ON CONFLICT (id) DO NOTHING;

-- Configurăm politicile implicite de storage pentru "attachments"
DO $$ 
BEGIN
-- Excludem erori in caz ca exista deja politicile 
  CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'attachments');
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END $$;

DO $$ 
BEGIN
  CREATE POLICY "Auth Insert" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'attachments');
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END $$;


-- 9. Activare Securitate (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- 10. Politici de Acces (Toate permise autentificaților)
DO $$ BEGIN
    CREATE POLICY "Acces Universal Sarcini" ON public.tasks FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Proiecte" ON public.projects FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Alerte" ON public.tbp_alerts FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Tranzacții" ON public.tbp_transactions FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Documente" ON public.documents FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Mesaje" ON public.messages FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE POLICY "Acces Universal Activitati" ON public.activities FOR ALL USING (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 11. Activare Real-Time
-- Adăugăm tabelele la publication una câte una și ignorăm eroarea dacă există deja
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE tasks; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE tbp_alerts; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE projects; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE documents; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE messages; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE activities; EXCEPTION WHEN duplicate_object THEN NULL; WHEN OTHERS THEN NULL; END $$;

