-- 1. Create the Transactions Table
CREATE TABLE IF NOT EXISTS public.tbp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    vendor TEXT,
    category TEXT,
    is_recurring BOOLEAN DEFAULT FALSE,
    type TEXT CHECK (type IN ('income', 'expense')),
    owner_id UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.tbp_transactions ENABLE ROW LEVEL SECURITY;

-- 3. Create Security Policies
-- Replace the email with your actual administrative email if needed, 
-- or use the 'owner' role logic if you have a roles table.
CREATE POLICY "Finance Pulse: Owner Read Access" 
ON public.tbp_transactions
FOR SELECT
USING (auth.jwt() ->> 'email' = 'rozaliamarinescu33@gmail.com');

CREATE POLICY "Finance Pulse: Owner Insert Access" 
ON public.tbp_transactions
FOR INSERT
WITH CHECK (auth.jwt() ->> 'email' = 'rozaliamarinescu33@gmail.com');

CREATE POLICY "Finance Pulse: Owner Delete Access" 
ON public.tbp_transactions
FOR DELETE
USING (auth.jwt() ->> 'email' = 'rozaliamarinescu33@gmail.com');

-- 4. Create Storage Bucket for Statements
-- Note: You should also create a bucket named 'finance-statements' 
-- in the Supabase Dashboard, set it to PRIVATE.
-- Then add these policies for storage:

-- INSERT policy for finance-statements bucket
-- SELECT policy for finance-statements bucket (Owner only)
