-- FINAL CONSOLIDATED SCHEMA FOR TBP PULSE
-- Run this in Supabase SQL Editor to fix all sync issues.

-- 1. Table: Projects (Clients)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    client TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    assignees TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    instructions TEXT,
    deadline TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    assignee TEXT,
    project_id BIGINT REFERENCES public.projects(id),
    attachments TEXT[] DEFAULT '{}', 
    attachment TEXT, 
    priority TEXT DEFAULT 'Medium',
    task_type TEXT DEFAULT 'General',
    block_reason TEXT,
    client TEXT, 
    reviewer TEXT,
    created_by TEXT,
    moved_to_review_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: Documents (Missing in original schema)
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    name TEXT NOT NULL,
    size TEXT,
    url TEXT NOT NULL,
    uploader TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: TBP Alerts
CREATE TABLE IF NOT EXISTS public.tbp_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    client TEXT,
    assignee TEXT,
    assignee_initials TEXT,
    assignee_color TEXT,
    error_code TEXT,
    severity TEXT CHECK (severity IN ('critical', 'warning', 'info')),
    is_resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    resolution_note TEXT,
    read_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: Transactions
CREATE TABLE IF NOT EXISTS public.tbp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    vendor TEXT,
    category TEXT,
    is_recurring BOOLEAN DEFAULT FALSE,
    type TEXT CHECK (type IN ('income', 'expense')),
    owner_id UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Storage Setup (Bucket for attachments)
-- This creates the bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('attachments', 'attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies for 'attachments'
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'attachments');
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'attachments' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated Update" ON storage.objects FOR UPDATE WITH CHECK (bucket_id = 'attachments' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated Delete" ON storage.objects FOR DELETE USING (bucket_id = 'attachments' AND auth.role() = 'authenticated');

-- 7. Real-time Setup
-- Enable real-time for core tables
ALTER PUBLICATION supabase_realtime ADD TABLE tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE tbp_alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE projects;
ALTER PUBLICATION supabase_realtime ADD TABLE documents;

-- 8. Security (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_transactions ENABLE ROW LEVEL SECURITY;

-- universal access policies for authenticated users
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Universal Access Tasks') THEN
        CREATE POLICY "Universal Access Tasks" ON public.tasks FOR ALL USING (auth.role() = 'authenticated');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Universal Access Projects') THEN
        CREATE POLICY "Universal Access Projects" ON public.projects FOR ALL USING (auth.role() = 'authenticated');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Universal Access Alerts') THEN
        CREATE POLICY "Universal Access Alerts" ON public.tbp_alerts FOR ALL USING (auth.role() = 'authenticated');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Universal Access Docs') THEN
        CREATE POLICY "Universal Access Docs" ON public.documents FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- Finance Pulse: Strict Rozalia
CREATE POLICY "Finance Rozalia Access" 
ON public.tbp_transactions
FOR ALL
USING (auth.jwt() ->> 'email' = 'rozaliamarinescu33@gmail.com');

-- 9. Fix existing columns if table already existed
DO $$ 
BEGIN 
    -- Fix tasks.attachments
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='attachments') THEN
        ALTER TABLE public.tasks ADD COLUMN attachments TEXT[] DEFAULT '{}';
    END IF;
    
    -- Fix tasks.client
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='client') THEN
        ALTER TABLE public.tasks ADD COLUMN client TEXT;
    END IF;

    -- Fix tasks.reviewer
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='reviewer') THEN
        ALTER TABLE public.tasks ADD COLUMN reviewer TEXT;
    END IF;

    -- Fix tasks.created_by
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='created_by') THEN
        ALTER TABLE public.tasks ADD COLUMN created_by TEXT;
    END IF;

    -- Fix tasks.instructions
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='tasks' AND column_name='instructions') THEN
        ALTER TABLE public.tasks ADD COLUMN instructions TEXT;
    END IF;

    -- Fix projects.name
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='name') THEN
        ALTER TABLE public.projects ADD COLUMN name TEXT;
    END IF;
    
    -- Update names from client if empty
    UPDATE public.projects SET name = client WHERE name IS NULL OR name = '';

    -- Fix projects.assignees
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='assignees') THEN
        ALTER TABLE public.projects ADD COLUMN assignees TEXT[] DEFAULT '{}';
    END IF;
END $$;

-- Force Cache Reload
NOTIFY pgrst, 'reload schema';
