-- Consolidat SQL Migration for TBP Pulse
-- Acest script creează toate tabelele necesare și configurează securitatea (RLS).

-- 1. Tabel: Proiecte (Clienți)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel: Sarcini (Tasks)
CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    instructions TEXT,
    deadline TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    assignee TEXT,
    project_id BIGINT REFERENCES public.projects(id),
    attachment TEXT,
    priority TEXT,
    task_type TEXT,
    block_reason TEXT,
    moved_to_review_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel: Alerte (TBP Alerts)
CREATE TABLE IF NOT EXISTS public.tbp_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    client TEXT,
    assignee TEXT,
    assignee_initials TEXT,
    assignee_color TEXT,
    error_code TEXT,
    severity TEXT CHECK (severity IN ('critical', 'warning', 'info')),
    is_resolved BOOLEAN DEFAULT FALSE,
    resolved_at TIMESTAMPTZ,
    resolution_note TEXT,
    read_at TIMESTAMPTZ,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel: Tranzacții Financiare (Finance Pulse)
CREATE TABLE IF NOT EXISTS public.tbp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    vendor TEXT,
    category TEXT,
    is_recurring BOOLEAN DEFAULT FALSE,
    type TEXT CHECK (type IN ('income', 'expense')),
    owner_id UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Activare Real-time
-- Notă: În interfața Supabase, trebuie să bifezi manual tabelele în tabelul 'supabase_realtime' publication.
-- Sau rulează aceste comenzi (dacă publication există deja):
ALTER PUBLICATION supabase_realtime ADD TABLE tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE tbp_alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE projects;

-- 6. Activare Securitate (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tbp_transactions ENABLE ROW LEVEL SECURITY;

-- 7. Politici de Acces (Exemplu pentru Rozalia)
-- Sarcini și Proiecte: Toată lumea cu login poate citi/edita
CREATE POLICY "Acces Universal Sarcini" ON public.tasks FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acces Universal Proiecte" ON public.projects FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Acces Universal Alerte" ON public.tbp_alerts FOR ALL USING (auth.role() = 'authenticated');

-- Finance Pulse: Strict Rozalia
CREATE POLICY "Finance Rozalia Access" 
ON public.tbp_transactions
FOR ALL
USING (auth.jwt() ->> 'email' = 'rozaliamarinescu33@gmail.com');
